version: "3.3"

services:
  mysql-server:
    image: mysql:8.0
    container_name: zabbix-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - zbx_net

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-7.4-latest
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    depends_on:
      - mysql-server
    ports:
      - "10051:10051"
    networks:
      - zbx_net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-7.4-latest
    container_name: zabbix-web
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      PHP_TZ: Asia/Kolkata
    depends_on:
      - mysql-server
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      - zbx_net

volumes:
  mysql_data:

networks:
  zbx_net:
